import***REMOVED***{***REMOVED***createRouter,***REMOVED***createWebHistory***REMOVED***}***REMOVED***from***REMOVED***'vue-router'
import***REMOVED***Home***REMOVED***from***REMOVED***'@/views/Home.vue'
import***REMOVED***Search***REMOVED***from***REMOVED***'@/views/Search.vue'
import***REMOVED***Discover***REMOVED***from***REMOVED***'@/views/Discover.vue'
import***REMOVED***Playlist***REMOVED***from***REMOVED***'@/views/Playlist.vue'
import***REMOVED***Rank***REMOVED***from***REMOVED***'@/views/Rank.vue'
import***REMOVED***MyMusic***REMOVED***from***REMOVED***'@/views/MyMusic.vue'
import***REMOVED***Favorites***REMOVED***from***REMOVED***'@/views/Favorites.vue'
import***REMOVED***Recent***REMOVED***from***REMOVED***'@/views/Recent.vue'

const***REMOVED***router***REMOVED***=***REMOVED***createRouter({
***REMOVED******REMOVED***history:***REMOVED***createWebHistory(),
***REMOVED******REMOVED***routes:***REMOVED***[
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***'/',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***'home',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***component:***REMOVED***Home
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***'/search',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***'search',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***component:***REMOVED***Search
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***'/discover',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***'discover',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***component:***REMOVED***Discover
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***'/playlist',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***'playlist',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***component:***REMOVED***Playlist
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***'/playlist/:id',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***'playlist-detail',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***component:***REMOVED***Playlist
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***'/rank',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***'rank',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***component:***REMOVED***Rank
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***'/my-music',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***'my-music',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***component:***REMOVED***MyMusic
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***'/favorites',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***'favorites',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***component:***REMOVED***Favorites
***REMOVED******REMOVED******REMOVED******REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***path:***REMOVED***'/recent',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***name:***REMOVED***'recent',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***component:***REMOVED***Recent
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***]
})

export***REMOVED***default***REMOVED***router
