import***REMOVED***{***REMOVED***defineStore***REMOVED***}***REMOVED***from***REMOVED***'pinia'
import***REMOVED***{***REMOVED***ref,***REMOVED***computed***REMOVED***}***REMOVED***from***REMOVED***'vue'
import***REMOVED***axios***REMOVED***from***REMOVED***'axios'

export***REMOVED***interface***REMOVED***Music***REMOVED***{
***REMOVED******REMOVED***id:***REMOVED***number
***REMOVED******REMOVED***mid:***REMOVED***string
***REMOVED******REMOVED***song:***REMOVED***string
***REMOVED******REMOVED***singer:***REMOVED***string
***REMOVED******REMOVED***album:***REMOVED***string
***REMOVED******REMOVED***cover:***REMOVED***string
***REMOVED******REMOVED***time?:***REMOVED***string
***REMOVED******REMOVED***pay?:***REMOVED***string
}

export***REMOVED***interface***REMOVED***Playlist***REMOVED***{
***REMOVED******REMOVED***id:***REMOVED***number
***REMOVED******REMOVED***name:***REMOVED***string
***REMOVED******REMOVED***description:***REMOVED***string
***REMOVED******REMOVED***cover:***REMOVED***string
***REMOVED******REMOVED***userId:***REMOVED***number
***REMOVED******REMOVED***createdAt:***REMOVED***string
***REMOVED******REMOVED***updatedAt:***REMOVED***string
***REMOVED******REMOVED***musicList?:***REMOVED***PlaylistMusic[]
***REMOVED******REMOVED***musicCount:***REMOVED***number
}

export***REMOVED***interface***REMOVED***PlaylistMusic***REMOVED***{
***REMOVED******REMOVED***id:***REMOVED***number
***REMOVED******REMOVED***playlistId:***REMOVED***number
***REMOVED******REMOVED***musicId:***REMOVED***number
***REMOVED******REMOVED***musicMid:***REMOVED***string
***REMOVED******REMOVED***musicSong:***REMOVED***string
***REMOVED******REMOVED***musicSinger:***REMOVED***string
***REMOVED******REMOVED***musicAlbum:***REMOVED***string
***REMOVED******REMOVED***musicCover:***REMOVED***string
***REMOVED******REMOVED***musicUrl:***REMOVED***string
***REMOVED******REMOVED***sortOrder:***REMOVED***number
***REMOVED******REMOVED***addedAt:***REMOVED***string
}

export***REMOVED***const***REMOVED***useMusicStore***REMOVED***=***REMOVED***defineStore('music',***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***//***REMOVED***状态
***REMOVED******REMOVED***const***REMOVED***currentMusic***REMOVED***=***REMOVED***ref<Music***REMOVED***|***REMOVED***null>(null)
***REMOVED******REMOVED***const***REMOVED***musicList***REMOVED***=***REMOVED***ref<Music[]>([])
***REMOVED******REMOVED***const***REMOVED***isPlaying***REMOVED***=***REMOVED***ref(false)
***REMOVED******REMOVED***const***REMOVED***isLoading***REMOVED***=***REMOVED***ref(false)
***REMOVED******REMOVED***const***REMOVED***searchKeyword***REMOVED***=***REMOVED***ref('')
***REMOVED******REMOVED***const***REMOVED***audio***REMOVED***=***REMOVED***ref<HTMLAudioElement***REMOVED***|***REMOVED***null>(null)
***REMOVED******REMOVED***const***REMOVED***currentTime***REMOVED***=***REMOVED***ref(0)
***REMOVED******REMOVED***const***REMOVED***duration***REMOVED***=***REMOVED***ref(0)
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***无限滚动相关状态
***REMOVED******REMOVED***const***REMOVED***currentPage***REMOVED***=***REMOVED***ref(1)
***REMOVED******REMOVED***const***REMOVED***hasMoreData***REMOVED***=***REMOVED***ref(true)
***REMOVED******REMOVED***const***REMOVED***isLoadingMore***REMOVED***=***REMOVED***ref(false)
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***播放队列相关状态
***REMOVED******REMOVED***const***REMOVED***playQueue***REMOVED***=***REMOVED***ref<Music[]>([])
***REMOVED******REMOVED***const***REMOVED***showPlayQueue***REMOVED***=***REMOVED***ref(false)

***REMOVED******REMOVED***//***REMOVED***计算属性
***REMOVED******REMOVED***const***REMOVED***hasCurrentMusic***REMOVED***=***REMOVED***computed(()***REMOVED***=>***REMOVED***currentMusic.value***REMOVED***!==***REMOVED***null)
***REMOVED******REMOVED***const***REMOVED***progress***REMOVED***=***REMOVED***computed(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(duration.value***REMOVED***===***REMOVED***0)***REMOVED***return***REMOVED***0
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***(currentTime.value***REMOVED***/***REMOVED***duration.value)***REMOVED*******REMOVED***100
***REMOVED******REMOVED***})
***REMOVED******REMOVED***const***REMOVED***queueCount***REMOVED***=***REMOVED***computed(()***REMOVED***=>***REMOVED***playQueue.value.length)

***REMOVED******REMOVED***//***REMOVED***初始化音频
***REMOVED******REMOVED***const***REMOVED***initAudio***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***audio.value***REMOVED***=***REMOVED***new***REMOVED***Audio()
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***audio.value.addEventListener('timeupdate',***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***currentTime.value***REMOVED***=***REMOVED***audio.value?.currentTime***REMOVED***||***REMOVED***0
***REMOVED******REMOVED******REMOVED******REMOVED***})
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***audio.value.addEventListener('loadedmetadata',***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***duration.value***REMOVED***=***REMOVED***audio.value?.duration***REMOVED***||***REMOVED***0
***REMOVED******REMOVED******REMOVED******REMOVED***})
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***audio.value.addEventListener('ended',***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***isPlaying.value***REMOVED***=***REMOVED***false
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***自动播放下一首
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***playNext()
***REMOVED******REMOVED******REMOVED******REMOVED***})
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***搜索音乐（首次搜索）
***REMOVED******REMOVED***const***REMOVED***searchMusic***REMOVED***=***REMOVED***async***REMOVED***(keyword:***REMOVED***string)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!keyword.trim())***REMOVED***return
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***isLoading.value***REMOVED***=***REMOVED***true
***REMOVED******REMOVED******REMOVED******REMOVED***searchKeyword.value***REMOVED***=***REMOVED***keyword
***REMOVED******REMOVED******REMOVED******REMOVED***currentPage.value***REMOVED***=***REMOVED***1
***REMOVED******REMOVED******REMOVED******REMOVED***hasMoreData.value***REMOVED***=***REMOVED***true
***REMOVED******REMOVED******REMOVED******REMOVED***musicList.value***REMOVED***=***REMOVED***[]
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***console.log('🔍***REMOVED***开始搜索音乐，关键词:',***REMOVED***keyword)
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***apiUrl***REMOVED***=***REMOVED***'/api/music/search'
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***params***REMOVED***=***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***keyword:***REMOVED***keyword,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***page:***REMOVED***1,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***size:***REMOVED***20
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('📡***REMOVED***调用后端API:',***REMOVED***apiUrl,***REMOVED***params)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***res***REMOVED***=***REMOVED***await***REMOVED***axios.get(apiUrl,***REMOVED***{***REMOVED***params***REMOVED***})
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('✅***REMOVED***后端API响应:',***REMOVED***res.data)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(res.data.code***REMOVED***===***REMOVED***200)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***newMusicList***REMOVED***=***REMOVED***res.data.data***REMOVED***||***REMOVED***[]
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***musicList.value***REMOVED***=***REMOVED***newMusicList
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***检查是否还有更多数据
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hasMoreData.value***REMOVED***=***REMOVED***newMusicList.length***REMOVED***>=***REMOVED***20
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('🎵***REMOVED***首次搜索完成，获得',***REMOVED***newMusicList.length,***REMOVED***'首歌曲')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('📄***REMOVED***是否还有更多数据:',***REMOVED***hasMoreData.value)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***throw***REMOVED***new***REMOVED***Error(res.data.message***REMOVED***||***REMOVED***'搜索失败')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error:***REMOVED***any)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.error('❌***REMOVED***搜索音乐失败:',***REMOVED***error)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.error('错误详情:',***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***message:***REMOVED***error.message,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***status:***REMOVED***error.response?.status,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***statusText:***REMOVED***error.response?.statusText,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***data:***REMOVED***error.response?.data
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***})
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***musicList.value***REMOVED***=***REMOVED***[]
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hasMoreData.value***REMOVED***=***REMOVED***false
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***finally***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***isLoading.value***REMOVED***=***REMOVED***false
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***加载更多音乐
***REMOVED******REMOVED***const***REMOVED***loadMoreMusic***REMOVED***=***REMOVED***async***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!hasMoreData.value***REMOVED***||***REMOVED***isLoadingMore.value***REMOVED***||***REMOVED***!searchKeyword.value.trim())***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***isLoadingMore.value***REMOVED***=***REMOVED***true
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***nextPage***REMOVED***=***REMOVED***currentPage.value***REMOVED***+***REMOVED***1
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***console.log('📄***REMOVED***加载更多音乐，页码:',***REMOVED***nextPage)
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***apiUrl***REMOVED***=***REMOVED***'/api/music/search'
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***params***REMOVED***=***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***keyword:***REMOVED***searchKeyword.value,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***page:***REMOVED***nextPage,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***size:***REMOVED***20
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***res***REMOVED***=***REMOVED***await***REMOVED***axios.get(apiUrl,***REMOVED***{***REMOVED***params***REMOVED***})
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(res.data.code***REMOVED***===***REMOVED***200)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***newMusicList***REMOVED***=***REMOVED***res.data.data***REMOVED***||***REMOVED***[]
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(newMusicList.length***REMOVED***>***REMOVED***0)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***将新数据追加到现有列表
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***musicList.value***REMOVED***=***REMOVED***[...musicList.value,***REMOVED***...newMusicList]
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***currentPage.value***REMOVED***=***REMOVED***nextPage
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***检查是否还有更多数据
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hasMoreData.value***REMOVED***=***REMOVED***newMusicList.length***REMOVED***>=***REMOVED***20
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('✅***REMOVED***加载更多成功，新增',***REMOVED***newMusicList.length,***REMOVED***'首歌曲')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('📊***REMOVED***总歌曲数:',***REMOVED***musicList.value.length)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('📄***REMOVED***是否还有更多数据:',***REMOVED***hasMoreData.value)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hasMoreData.value***REMOVED***=***REMOVED***false
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('📄***REMOVED***没有更多数据了')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***throw***REMOVED***new***REMOVED***Error(res.data.message***REMOVED***||***REMOVED***'加载更多失败')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.error('❌***REMOVED***加载更多音乐失败:',***REMOVED***error)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***hasMoreData.value***REMOVED***=***REMOVED***false
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***finally***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***isLoadingMore.value***REMOVED***=***REMOVED***false
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***}

***REMOVED******REMOVED***const***REMOVED***getMusicPlayUrl***REMOVED***=***REMOVED***async***REMOVED***(music:***REMOVED***Music)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***apiUrl***REMOVED***=***REMOVED***'/api/music/url'
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***params***REMOVED***=***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***...(music.mid***REMOVED***?***REMOVED***{***REMOVED***mid***REMOVED***:***REMOVED***music.mid***REMOVED***}***REMOVED***:***REMOVED***{***REMOVED***id***REMOVED***:***REMOVED***music.id***REMOVED***})
***REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED***console.log('🎵***REMOVED***获取播放URL:',***REMOVED***apiUrl,***REMOVED***params)

***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***res***REMOVED***=***REMOVED***await***REMOVED***axios.get(apiUrl,***REMOVED***{***REMOVED***params***REMOVED***})
***REMOVED******REMOVED******REMOVED******REMOVED***if(res.data.code***REMOVED***!==***REMOVED***200)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***throw***REMOVED***new***REMOVED***Error(res.data.message***REMOVED***||***REMOVED***'获取播放URL失败')
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***if(!res.data.data?.url)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***throw***REMOVED***new***REMOVED***Error('获取音乐播放URL失败')
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***res.data.data
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***下载音乐
***REMOVED******REMOVED***const***REMOVED***downloadMusic***REMOVED***=***REMOVED***async***REMOVED***(music:***REMOVED***Music)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('⬇️***REMOVED***开始下载音乐:',***REMOVED***music.song)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***获取音乐播放URL（这个URL就是音乐文件的直链）
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***musicData***REMOVED***=***REMOVED***await***REMOVED***getMusicPlayUrl(music)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!musicData.url)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***throw***REMOVED***new***REMOVED***Error('获取音乐下载链接失败')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***使用fetch获取文件内容
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***response***REMOVED***=***REMOVED***await***REMOVED***fetch(musicData.url,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***method:***REMOVED***'GET',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***headers:***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***'User-Agent':***REMOVED***'Mozilla/5.0***REMOVED***(Windows***REMOVED***NT***REMOVED***10.0;***REMOVED***Win64;***REMOVED***x64)***REMOVED***AppleWebKit/537.36'
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***})
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!response.ok)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***throw***REMOVED***new***REMOVED***Error(`下载失败:***REMOVED***${response.status}***REMOVED***${response.statusText}`)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***获取文件内容
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***blob***REMOVED***=***REMOVED***await***REMOVED***response.blob()
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***创建blob***REMOVED***URL
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***blobUrl***REMOVED***=***REMOVED***URL.createObjectURL(blob)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***创建下载链接
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***link***REMOVED***=***REMOVED***document.createElement('a')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***link.href***REMOVED***=***REMOVED***blobUrl
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***link.download***REMOVED***=***REMOVED***`${music.song}***REMOVED***-***REMOVED***${music.singer}.${musicData.format***REMOVED***||***REMOVED***'mp3'}`
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***触发下载
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***document.body.appendChild(link)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***link.click()
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***document.body.removeChild(link)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***清理blob***REMOVED***URL
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***setTimeout(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***URL.revokeObjectURL(blobUrl)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***},***REMOVED***1000)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('✅***REMOVED***音乐下载已开始:',***REMOVED***music.song)
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.error('❌***REMOVED***下载音乐失败:',***REMOVED***error)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***throw***REMOVED***error
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***播放音乐
***REMOVED******REMOVED***const***REMOVED***playMusic***REMOVED***=***REMOVED***async***REMOVED***(music:***REMOVED***Music)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!audio.value)***REMOVED***return
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***如果点击的是当前正在播放的音乐，则切换播放/暂停状态
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(currentMusic.value***REMOVED***&&***REMOVED***currentMusic.value.id***REMOVED***===***REMOVED***music.id)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***togglePlay()
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***如果是新音乐，则开始播放
***REMOVED******REMOVED******REMOVED******REMOVED***currentMusic.value***REMOVED***=***REMOVED***music
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***musicData***REMOVED***=***REMOVED***await***REMOVED***getMusicPlayUrl(music)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if(!audio.value.paused***REMOVED***)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***audio.value.pause()
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***audio.value.src***REMOVED***=***REMOVED***musicData.url
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***audio.value.play()
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***isPlaying.value***REMOVED***=***REMOVED***true
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.error('播放音乐失败:',***REMOVED***error)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***audio.value.src***REMOVED***=***REMOVED***''
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***isPlaying.value***REMOVED***=***REMOVED***false
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***currentMusic.value***REMOVED***=***REMOVED***null
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***暂停/继续播放
***REMOVED******REMOVED***const***REMOVED***togglePlay***REMOVED***=***REMOVED***async***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!audio.value***REMOVED***||***REMOVED***!currentMusic.value)***REMOVED***return
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(isPlaying.value)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***audio.value.pause()
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***isPlaying.value***REMOVED***=***REMOVED***false
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***audio.value.play()
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***isPlaying.value***REMOVED***=***REMOVED***true
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(error)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.error('切换播放状态失败:',***REMOVED***error)
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***停止播放
***REMOVED******REMOVED***const***REMOVED***stopMusic***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!audio.value)***REMOVED***return
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***audio.value.pause()
***REMOVED******REMOVED******REMOVED******REMOVED***audio.value.currentTime***REMOVED***=***REMOVED***0
***REMOVED******REMOVED******REMOVED******REMOVED***isPlaying.value***REMOVED***=***REMOVED***false
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***设置播放进度
***REMOVED******REMOVED***const***REMOVED***setProgress***REMOVED***=***REMOVED***(percent:***REMOVED***number)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!audio.value***REMOVED***||***REMOVED***!duration.value)***REMOVED***return
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***time***REMOVED***=***REMOVED***(percent***REMOVED***/***REMOVED***100)***REMOVED*******REMOVED***duration.value
***REMOVED******REMOVED******REMOVED******REMOVED***audio.value.currentTime***REMOVED***=***REMOVED***time
***REMOVED******REMOVED******REMOVED******REMOVED***currentTime.value***REMOVED***=***REMOVED***time
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***==========***REMOVED***播放队列相关方法***REMOVED***==========
***REMOVED******REMOVED***
***REMOVED******REMOVED***//***REMOVED***添加音乐到播放队列
***REMOVED******REMOVED***const***REMOVED***addToQueue***REMOVED***=***REMOVED***(music:***REMOVED***Music)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***检查是否已经在队列中
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***existingIndex***REMOVED***=***REMOVED***playQueue.value.findIndex(item***REMOVED***=>***REMOVED***item.id***REMOVED***===***REMOVED***music.id)
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(existingIndex***REMOVED***>***REMOVED***-1)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***如果已存在，将其移到队列最前面
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***existingMusic***REMOVED***=***REMOVED***playQueue.value.splice(existingIndex,***REMOVED***1)[0]
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***playQueue.value.unshift(existingMusic)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('🎵***REMOVED***音乐已移到队列最前面:',***REMOVED***music.song)
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***如果不存在，添加到队列末尾
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***playQueue.value.push(music)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('🎵***REMOVED***添加音乐到播放队列:',***REMOVED***music.song)
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***自动显示播放队列面板
***REMOVED******REMOVED******REMOVED******REMOVED***showPlayQueue.value***REMOVED***=***REMOVED***true
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***从播放队列移除音乐
***REMOVED******REMOVED***const***REMOVED***removeFromQueue***REMOVED***=***REMOVED***(musicId:***REMOVED***number)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***index***REMOVED***=***REMOVED***playQueue.value.findIndex(item***REMOVED***=>***REMOVED***item.id***REMOVED***===***REMOVED***musicId)
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(index***REMOVED***>***REMOVED***-1)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***playQueue.value.splice(index,***REMOVED***1)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('🗑️***REMOVED***从播放队列移除音乐')
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***清空播放队列
***REMOVED******REMOVED***const***REMOVED***clearQueue***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***playQueue.value***REMOVED***=***REMOVED***[]
***REMOVED******REMOVED******REMOVED******REMOVED***console.log('🗑️***REMOVED***清空播放队列')
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***播放下一首
***REMOVED******REMOVED***const***REMOVED***playNext***REMOVED***=***REMOVED***async***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(playQueue.value.length***REMOVED***>***REMOVED***0)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***nextMusic***REMOVED***=***REMOVED***playQueue.value.shift()***REMOVED***//***REMOVED***从队列头部移除
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(nextMusic)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('⏭️***REMOVED***自动播放下一首:',***REMOVED***nextMusic.song)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***playMusic(nextMusic)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('📭***REMOVED***播放队列为空')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***currentMusic.value***REMOVED***=***REMOVED***null
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***isPlaying.value***REMOVED***=***REMOVED***false
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***播放上一首（从队列末尾添加）
***REMOVED******REMOVED***const***REMOVED***playPrevious***REMOVED***=***REMOVED***async***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(playQueue.value.length***REMOVED***>***REMOVED***0)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***prevMusic***REMOVED***=***REMOVED***playQueue.value.pop()***REMOVED***//***REMOVED***从队列末尾移除
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(prevMusic)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('⏮️***REMOVED***播放上一首:',***REMOVED***prevMusic.song)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***playMusic(prevMusic)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***切换播放队列显示状态
***REMOVED******REMOVED***const***REMOVED***togglePlayQueue***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***showPlayQueue.value***REMOVED***=***REMOVED***!showPlayQueue.value
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***重新排列播放队列
***REMOVED******REMOVED***const***REMOVED***reorderQueue***REMOVED***=***REMOVED***(fromIndex:***REMOVED***number,***REMOVED***toIndex:***REMOVED***number)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***music***REMOVED***=***REMOVED***playQueue.value.splice(fromIndex,***REMOVED***1)[0]
***REMOVED******REMOVED******REMOVED******REMOVED***playQueue.value.splice(toIndex,***REMOVED***0,***REMOVED***music)
***REMOVED******REMOVED***}

***REMOVED******REMOVED***//***REMOVED***播放队列中的音乐（会将其移到最前面）
***REMOVED******REMOVED***const***REMOVED***playMusicFromQueue***REMOVED***=***REMOVED***async***REMOVED***(music:***REMOVED***Music)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***如果歌曲在队列中，先将其移到最前面
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***existingIndex***REMOVED***=***REMOVED***playQueue.value.findIndex(item***REMOVED***=>***REMOVED***item.id***REMOVED***===***REMOVED***music.id)
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(existingIndex***REMOVED***>***REMOVED***-1)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***existingMusic***REMOVED***=***REMOVED***playQueue.value.splice(existingIndex,***REMOVED***1)[0]
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***playQueue.value.unshift(existingMusic)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***console.log('🎵***REMOVED***歌曲已移到队列最前面:',***REMOVED***music.song)
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***播放音乐
***REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***playMusic(music)
***REMOVED******REMOVED***}


***REMOVED******REMOVED***return***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***状态
***REMOVED******REMOVED******REMOVED******REMOVED***currentMusic,
***REMOVED******REMOVED******REMOVED******REMOVED***musicList,
***REMOVED******REMOVED******REMOVED******REMOVED***isPlaying,
***REMOVED******REMOVED******REMOVED******REMOVED***isLoading,
***REMOVED******REMOVED******REMOVED******REMOVED***searchKeyword,
***REMOVED******REMOVED******REMOVED******REMOVED***currentTime,
***REMOVED******REMOVED******REMOVED******REMOVED***duration,
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***无限滚动状态
***REMOVED******REMOVED******REMOVED******REMOVED***currentPage,
***REMOVED******REMOVED******REMOVED******REMOVED***hasMoreData,
***REMOVED******REMOVED******REMOVED******REMOVED***isLoadingMore,
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***播放队列状态
***REMOVED******REMOVED******REMOVED******REMOVED***playQueue,
***REMOVED******REMOVED******REMOVED******REMOVED***showPlayQueue,
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***计算属性
***REMOVED******REMOVED******REMOVED******REMOVED***hasCurrentMusic,
***REMOVED******REMOVED******REMOVED******REMOVED***progress,
***REMOVED******REMOVED******REMOVED******REMOVED***queueCount,
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***方法
***REMOVED******REMOVED******REMOVED******REMOVED***initAudio,
***REMOVED******REMOVED******REMOVED******REMOVED***searchMusic,
***REMOVED******REMOVED******REMOVED******REMOVED***loadMoreMusic,
***REMOVED******REMOVED******REMOVED******REMOVED***playMusic,
***REMOVED******REMOVED******REMOVED******REMOVED***togglePlay,
***REMOVED******REMOVED******REMOVED******REMOVED***stopMusic,
***REMOVED******REMOVED******REMOVED******REMOVED***setProgress,
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***播放队列方法
***REMOVED******REMOVED******REMOVED******REMOVED***addToQueue,
***REMOVED******REMOVED******REMOVED******REMOVED***removeFromQueue,
***REMOVED******REMOVED******REMOVED******REMOVED***clearQueue,
***REMOVED******REMOVED******REMOVED******REMOVED***playNext,
***REMOVED******REMOVED******REMOVED******REMOVED***playPrevious,
***REMOVED******REMOVED******REMOVED******REMOVED***togglePlayQueue,
***REMOVED******REMOVED******REMOVED******REMOVED***reorderQueue,
***REMOVED******REMOVED******REMOVED******REMOVED***playMusicFromQueue,
***REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***下载方法
***REMOVED******REMOVED******REMOVED******REMOVED***downloadMusic
***REMOVED******REMOVED***}
})
