# Spring Boot 应用配置（公共部分）
server:
  port: 9092

spring:
  application:
    name: mymusic-springboot
  profiles:
    active: dev  # 默认使用开发环境，可通过命令覆盖

# MyBatis配置
mybatis:
  # mapper文件位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类包路径
  type-aliases-package: org.example.entity
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true

# 阿里云 OSS 配置（请改为你的实际信息，建议使用环境变量覆盖）
oss:
  bucket: my-music-avatar
  region: oss-cn-beijing
  endpoint: https://oss-cn-beijing.aliyuncs.com
  # 仅服务器端持有永久 AK/SK；请不要提交真实值到仓库
  # 使用环境变量，避免敏感信息泄露
  accessKeyId: ${ALIBABA_CLOUD_ACCESS_KEY_ID:your-access-key-id}
  accessKeySecret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET:your-access-key-secret}
  # 头像文件前缀
  avatarPrefix: avatars/
  # 直传回调可选：若需要 OSS 回调到你服务器，请再补充 callback