--***REMOVED***创建用户表
CREATE***REMOVED***TABLE***REMOVED***IF***REMOVED***NOT***REMOVED***EXISTS***REMOVED***`user`***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***`id`***REMOVED***BIGINT***REMOVED***AUTO_INCREMENT***REMOVED***PRIMARY***REMOVED***KEY***REMOVED***COMMENT***REMOVED***'用户ID',
***REMOVED******REMOVED******REMOVED******REMOVED***`username`***REMOVED***VARCHAR(50)***REMOVED***NOT***REMOVED***NULL***REMOVED***UNIQUE***REMOVED***COMMENT***REMOVED***'用户名',
***REMOVED******REMOVED******REMOVED******REMOVED***`password`***REMOVED***VARCHAR(255)***REMOVED***NOT***REMOVED***NULL***REMOVED***COMMENT***REMOVED***'密码',
***REMOVED******REMOVED******REMOVED******REMOVED***`nickname`***REMOVED***VARCHAR(50)***REMOVED***COMMENT***REMOVED***'昵称',
***REMOVED******REMOVED******REMOVED******REMOVED***`avatar`***REMOVED***VARCHAR(255)***REMOVED***COMMENT***REMOVED***'头像URL',
***REMOVED******REMOVED******REMOVED******REMOVED***`create_time`***REMOVED***DATETIME***REMOVED***DEFAULT***REMOVED***CURRENT_TIMESTAMP***REMOVED***COMMENT***REMOVED***'创建时间',
***REMOVED******REMOVED******REMOVED******REMOVED***`update_time`***REMOVED***DATETIME***REMOVED***DEFAULT***REMOVED***CURRENT_TIMESTAMP***REMOVED***ON***REMOVED***UPDATE***REMOVED***CURRENT_TIMESTAMP***REMOVED***COMMENT***REMOVED***'更新时间',
***REMOVED******REMOVED******REMOVED******REMOVED***`status`***REMOVED***TINYINT***REMOVED***DEFAULT***REMOVED***1***REMOVED***COMMENT***REMOVED***'状态：0-禁用，1-启用'
)***REMOVED***ENGINE=InnoDB***REMOVED***DEFAULT***REMOVED***CHARSET=utf8mb4***REMOVED***COLLATE=utf8mb4_unicode_ci***REMOVED***COMMENT='用户表';

--***REMOVED***插入测试用户数据
INSERT***REMOVED***INTO***REMOVED***`user`***REMOVED***(`username`,***REMOVED***`password`,***REMOVED***`nickname`,***REMOVED***`avatar`,***REMOVED***`status`)***REMOVED***VALUES
('admin',***REMOVED***'admin123',***REMOVED***'管理员',***REMOVED***'https://picsum.photos/40/40?random=1',***REMOVED***1),
('test',***REMOVED***'test123',***REMOVED***'测试用户',***REMOVED***'https://picsum.photos/40/40?random=2',***REMOVED***1);
