--***REMOVED***创建用户播放列表表
CREATE***REMOVED***TABLE***REMOVED***IF***REMOVED***NOT***REMOVED***EXISTS***REMOVED***`user_playlist`***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***`id`***REMOVED***BIGINT***REMOVED***AUTO_INCREMENT***REMOVED***PRIMARY***REMOVED***KEY***REMOVED***COMMENT***REMOVED***'播放列表ID',
***REMOVED******REMOVED******REMOVED******REMOVED***`user_id`***REMOVED***BIGINT***REMOVED***NOT***REMOVED***NULL***REMOVED***COMMENT***REMOVED***'用户ID',
***REMOVED******REMOVED******REMOVED******REMOVED***`name`***REMOVED***VARCHAR(100)***REMOVED***NOT***REMOVED***NULL***REMOVED***COMMENT***REMOVED***'播放列表名称',
***REMOVED******REMOVED******REMOVED******REMOVED***`description`***REMOVED***TEXT***REMOVED***COMMENT***REMOVED***'播放列表描述',
***REMOVED******REMOVED******REMOVED******REMOVED***`cover_url`***REMOVED***VARCHAR(255)***REMOVED***COMMENT***REMOVED***'封面图片URL',
***REMOVED******REMOVED******REMOVED******REMOVED***`create_time`***REMOVED***DATETIME***REMOVED***DEFAULT***REMOVED***CURRENT_TIMESTAMP***REMOVED***COMMENT***REMOVED***'创建时间',
***REMOVED******REMOVED******REMOVED******REMOVED***`update_time`***REMOVED***DATETIME***REMOVED***DEFAULT***REMOVED***CURRENT_TIMESTAMP***REMOVED***ON***REMOVED***UPDATE***REMOVED***CURRENT_TIMESTAMP***REMOVED***COMMENT***REMOVED***'更新时间',
***REMOVED******REMOVED******REMOVED******REMOVED***`status`***REMOVED***TINYINT***REMOVED***DEFAULT***REMOVED***1***REMOVED***COMMENT***REMOVED***'状态：0-删除，1-正常',
***REMOVED******REMOVED******REMOVED******REMOVED***FOREIGN***REMOVED***KEY***REMOVED***(`user_id`)***REMOVED***REFERENCES***REMOVED***`user`(`id`)***REMOVED***ON***REMOVED***DELETE***REMOVED***CASCADE
)***REMOVED***ENGINE=InnoDB***REMOVED***DEFAULT***REMOVED***CHARSET=utf8mb4***REMOVED***COLLATE=utf8mb4_unicode_ci***REMOVED***COMMENT='用户播放列表表';

--***REMOVED***创建播放列表音乐关联表
CREATE***REMOVED***TABLE***REMOVED***IF***REMOVED***NOT***REMOVED***EXISTS***REMOVED***`playlist_music`***REMOVED***(
***REMOVED******REMOVED******REMOVED******REMOVED***`id`***REMOVED***BIGINT***REMOVED***AUTO_INCREMENT***REMOVED***PRIMARY***REMOVED***KEY***REMOVED***COMMENT***REMOVED***'关联ID',
***REMOVED******REMOVED******REMOVED******REMOVED***`playlist_id`***REMOVED***BIGINT***REMOVED***NOT***REMOVED***NULL***REMOVED***COMMENT***REMOVED***'播放列表ID',
***REMOVED******REMOVED******REMOVED******REMOVED***`music_id`***REMOVED***VARCHAR(100)***REMOVED***NOT***REMOVED***NULL***REMOVED***COMMENT***REMOVED***'音乐ID',
***REMOVED******REMOVED******REMOVED******REMOVED***`music_name`***REMOVED***VARCHAR(200)***REMOVED***NOT***REMOVED***NULL***REMOVED***COMMENT***REMOVED***'音乐名称',
***REMOVED******REMOVED******REMOVED******REMOVED***`artist_name`***REMOVED***VARCHAR(200)***REMOVED***COMMENT***REMOVED***'艺术家名称',
***REMOVED******REMOVED******REMOVED******REMOVED***`album_name`***REMOVED***VARCHAR(200)***REMOVED***COMMENT***REMOVED***'专辑名称',
***REMOVED******REMOVED******REMOVED******REMOVED***`duration`***REMOVED***INT***REMOVED***COMMENT***REMOVED***'时长（秒）',
***REMOVED******REMOVED******REMOVED******REMOVED***`music_url`***REMOVED***VARCHAR(500)***REMOVED***COMMENT***REMOVED***'音乐文件URL',
***REMOVED******REMOVED******REMOVED******REMOVED***`cover_url`***REMOVED***VARCHAR(500)***REMOVED***COMMENT***REMOVED***'封面图片URL',
***REMOVED******REMOVED******REMOVED******REMOVED***`add_time`***REMOVED***DATETIME***REMOVED***DEFAULT***REMOVED***CURRENT_TIMESTAMP***REMOVED***COMMENT***REMOVED***'添加时间',
***REMOVED******REMOVED******REMOVED******REMOVED***`sort_order`***REMOVED***INT***REMOVED***DEFAULT***REMOVED***0***REMOVED***COMMENT***REMOVED***'排序顺序',
***REMOVED******REMOVED******REMOVED******REMOVED***FOREIGN***REMOVED***KEY***REMOVED***(`playlist_id`)***REMOVED***REFERENCES***REMOVED***`user_playlist`(`id`)***REMOVED***ON***REMOVED***DELETE***REMOVED***CASCADE
)***REMOVED***ENGINE=InnoDB***REMOVED***DEFAULT***REMOVED***CHARSET=utf8mb4***REMOVED***COLLATE=utf8mb4_unicode_ci***REMOVED***COMMENT='播放列表音乐关联表';

--***REMOVED***创建索引
CREATE***REMOVED***INDEX***REMOVED***idx_user_playlist_user_id***REMOVED***ON***REMOVED***`user_playlist`(`user_id`);
CREATE***REMOVED***INDEX***REMOVED***idx_playlist_music_playlist_id***REMOVED***ON***REMOVED***`playlist_music`(`playlist_id`);
CREATE***REMOVED***INDEX***REMOVED***idx_playlist_music_sort***REMOVED***ON***REMOVED***`playlist_music`(`playlist_id`,***REMOVED***`sort_order`);

