<template>
***REMOVED******REMOVED***<div***REMOVED***class="player-shell">
***REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***v-if="current"***REMOVED***class="player-page">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="left">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="disc-wrap">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="disc***REMOVED***spinning"***REMOVED***:class="{***REMOVED***paused:***REMOVED***!isPlaying***REMOVED***}"***REMOVED***@click="togglePlay">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<img***REMOVED***:src="current.cover"***REMOVED***alt="cover"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="center-hole"></div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="tips">点击封面{{***REMOVED***isPlaying***REMOVED***?***REMOVED***'暂停'***REMOVED***:***REMOVED***'播放'***REMOVED***}}</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="controls">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-button***REMOVED***type="text"***REMOVED***class="ctl"***REMOVED***@click="playPrevious">⏮️</el-button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-button***REMOVED***type="primary"***REMOVED***circle***REMOVED***class="play"***REMOVED***@click="togglePlay">{{***REMOVED***isPlaying***REMOVED***?***REMOVED***'⏸️'***REMOVED***:***REMOVED***'▶️'***REMOVED***}}</el-button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-button***REMOVED***type="text"***REMOVED***class="ctl"***REMOVED***@click="playNext">⏭️</el-button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="progress">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***class="time">{{***REMOVED***formatTime(currentTime)***REMOVED***}}</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-slider***REMOVED***:model-value="progress"***REMOVED***@input="setProgress"***REMOVED***:show-tooltip="false"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<span***REMOVED***class="time">{{***REMOVED***formatTime(duration)***REMOVED***}}</span>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="right">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="meta">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<h1***REMOVED***class="title">{{***REMOVED***current.song***REMOVED***}}</h1>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<p***REMOVED***class="artist">{{***REMOVED***current.singer***REMOVED***}}</p>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="lyrics"***REMOVED***v-if="lyricsLines.length">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***v-for="(line,***REMOVED***idx)***REMOVED***in***REMOVED***lyricsLines"***REMOVED***:key="idx"***REMOVED***:class="['line',***REMOVED***{***REMOVED***active:***REMOVED***idx***REMOVED***===***REMOVED***activeLineIndex***REMOVED***}]">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***{{***REMOVED***line.text***REMOVED***}}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***v-else***REMOVED***class="lyrics***REMOVED***empty">暂无歌词</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***v-else***REMOVED***class="empty">暂无正在播放的音乐</div>
***REMOVED******REMOVED***</div>
</template>

<script***REMOVED***setup***REMOVED***lang="ts">
import***REMOVED***{***REMOVED***computed,***REMOVED***ref,***REMOVED***watch,***REMOVED***onMounted***REMOVED***}***REMOVED***from***REMOVED***'vue'
import***REMOVED***{***REMOVED***useMusicStore***REMOVED***}***REMOVED***from***REMOVED***'../stores/music'
import***REMOVED***{***REMOVED***useUserStore***REMOVED***}***REMOVED***from***REMOVED***'../stores/user'

const***REMOVED***musicStore***REMOVED***=***REMOVED***useMusicStore()
const***REMOVED***userStore***REMOVED***=***REMOVED***useUserStore()

const***REMOVED***current***REMOVED***=***REMOVED***computed(()***REMOVED***=>***REMOVED***musicStore.currentMusic)
const***REMOVED***isPlaying***REMOVED***=***REMOVED***computed(()***REMOVED***=>***REMOVED***musicStore.isPlaying)
const***REMOVED***progress***REMOVED***=***REMOVED***computed(()***REMOVED***=>***REMOVED***musicStore.progress)
const***REMOVED***currentTime***REMOVED***=***REMOVED***computed(()***REMOVED***=>***REMOVED***musicStore.currentTime)
const***REMOVED***duration***REMOVED***=***REMOVED***computed(()***REMOVED***=>***REMOVED***musicStore.duration)

const***REMOVED***togglePlay***REMOVED***=***REMOVED***async***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***m***REMOVED***=***REMOVED***current.value***REMOVED***as***REMOVED***any
***REMOVED******REMOVED***if***REMOVED***(!m)***REMOVED***return
***REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***audioSrc***REMOVED***=***REMOVED***(musicStore***REMOVED***as***REMOVED***any).audio?.src***REMOVED***as***REMOVED***string***REMOVED***|***REMOVED***undefined
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***如果没有可用的音频源，则通过***REMOVED***playMusic***REMOVED***拉取并播放
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!audioSrc)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***musicStore.playMusic(m)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***已有音源：统一走***REMOVED***store***REMOVED***的***REMOVED***togglePlay，确保***REMOVED***isPlaying***REMOVED***状态与按钮/动画同步
***REMOVED******REMOVED******REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***musicStore.togglePlay()
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***catch***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***如遇播放失败，回退到重新拉取***REMOVED***URL
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***musicStore.playMusic(m)
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(e)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***静默失败，避免中断***REMOVED***UI；实际错误处理在***REMOVED***store***REMOVED***内完成
***REMOVED******REMOVED***}
}
const***REMOVED***playPrevious***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***musicStore.playPrevious()
const***REMOVED***playNext***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***musicStore.playNext()
const***REMOVED***setProgress***REMOVED***=***REMOVED***async***REMOVED***(v:***REMOVED***number)***REMOVED***=>***REMOVED***{***REMOVED***await***REMOVED***musicStore.setProgress(v)***REMOVED***}

//***REMOVED***简易歌词处理：从当前歌曲的***REMOVED***lyric***REMOVED***字段或通过已有***REMOVED***API***REMOVED***拉取（此处占位）
const***REMOVED***rawLyrics***REMOVED***=***REMOVED***ref<string>('')
const***REMOVED***lyricsLines***REMOVED***=***REMOVED***ref<Array<{***REMOVED***time:***REMOVED***number;***REMOVED***text:***REMOVED***string***REMOVED***}>>([])
const***REMOVED***activeLineIndex***REMOVED***=***REMOVED***ref<number>(-1)

const***REMOVED***parseLrc***REMOVED***=***REMOVED***(lrc:***REMOVED***string)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***lines***REMOVED***=***REMOVED***lrc.split(/\r?\n/)
***REMOVED******REMOVED***const***REMOVED***parsed:***REMOVED***Array<{***REMOVED***time:***REMOVED***number;***REMOVED***text:***REMOVED***string***REMOVED***}>***REMOVED***=***REMOVED***[]
***REMOVED******REMOVED***const***REMOVED***timeTag***REMOVED***=***REMOVED***/\[(\d{2}):(\d{2})(?:\.(\d{2,3}))?\]/
***REMOVED******REMOVED***for***REMOVED***(const***REMOVED***line***REMOVED***of***REMOVED***lines)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***match***REMOVED***=***REMOVED***line.match(timeTag)
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(match)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***mm***REMOVED***=***REMOVED***Number(match[1])
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***ss***REMOVED***=***REMOVED***Number(match[2])
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***ms***REMOVED***=***REMOVED***match[3]***REMOVED***?***REMOVED***Number(match[3].padEnd(3,***REMOVED***'0'))***REMOVED***:***REMOVED***0
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***t***REMOVED***=***REMOVED***mm***REMOVED*******REMOVED***60***REMOVED***+***REMOVED***ss***REMOVED***+***REMOVED***ms***REMOVED***/***REMOVED***1000
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***text***REMOVED***=***REMOVED***line.replace(timeTag,***REMOVED***'').trim()
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***parsed.push({***REMOVED***time:***REMOVED***t,***REMOVED***text***REMOVED***})
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***}
***REMOVED******REMOVED***parsed.sort((a,***REMOVED***b)***REMOVED***=>***REMOVED***a.time***REMOVED***-***REMOVED***b.time)
***REMOVED******REMOVED***return***REMOVED***parsed
}

watch(current,***REMOVED***async***REMOVED***(m)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***lyricsLines.value***REMOVED***=***REMOVED***[]
***REMOVED******REMOVED***activeLineIndex.value***REMOVED***=***REMOVED***-1
***REMOVED******REMOVED***rawLyrics.value***REMOVED***=***REMOVED***''
***REMOVED******REMOVED***//***REMOVED***TODO:***REMOVED***若后端有歌词接口，可在此请求并赋值***REMOVED***rawLyrics.value
},***REMOVED***{***REMOVED***immediate:***REMOVED***true***REMOVED***})

watch(currentTime,***REMOVED***(t)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***idx***REMOVED***=***REMOVED***lyricsLines.value.findIndex((l,***REMOVED***i)***REMOVED***=>***REMOVED***t***REMOVED***>=***REMOVED***l.time***REMOVED***&&***REMOVED***(i***REMOVED***===***REMOVED***lyricsLines.value.length***REMOVED***-***REMOVED***1***REMOVED***||***REMOVED***t***REMOVED***<***REMOVED***lyricsLines.value[i***REMOVED***+***REMOVED***1].time))
***REMOVED******REMOVED***activeLineIndex.value***REMOVED***=***REMOVED***idx
})

const***REMOVED***formatTime***REMOVED***=***REMOVED***(seconds:***REMOVED***number)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***mins***REMOVED***=***REMOVED***Math.floor(seconds***REMOVED***/***REMOVED***60)
***REMOVED******REMOVED***const***REMOVED***secs***REMOVED***=***REMOVED***Math.floor(seconds***REMOVED***%***REMOVED***60)
***REMOVED******REMOVED***return***REMOVED***`${mins.toString().padStart(2,***REMOVED***'0')}:${secs.toString().padStart(2,***REMOVED***'0')}`
}

onMounted(async***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***//***REMOVED***直接进入***REMOVED***/player***REMOVED***时，确保音频已初始化即可；避免在此恢复设置导致进度回退
***REMOVED******REMOVED***if***REMOVED***(!(musicStore***REMOVED***as***REMOVED***any).audio)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***musicStore.initAudio()
***REMOVED******REMOVED***}
***REMOVED******REMOVED***if***REMOVED***(!userStore.currentUser)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***await***REMOVED***userStore.initUserInfo?.()
***REMOVED******REMOVED***}
})
</script>

<style***REMOVED***scoped>
.player-shell***REMOVED***{***REMOVED***min-height:***REMOVED***calc(100vh***REMOVED***-***REMOVED***80px);***REMOVED***background:***REMOVED***radial-gradient(1200px***REMOVED***600px***REMOVED***at***REMOVED***20%***REMOVED***10%,***REMOVED***#7c83ff***REMOVED***0%,***REMOVED***#6c5ce7***REMOVED***25%,***REMOVED***#6f42c1***REMOVED***55%,***REMOVED***#51327a***REMOVED***100%);***REMOVED***padding:***REMOVED***24px***REMOVED***0;***REMOVED***}
.player-page***REMOVED***{***REMOVED***max-width:***REMOVED***1280px;***REMOVED***margin:***REMOVED***0***REMOVED***auto;***REMOVED***padding:***REMOVED***0***REMOVED***24px;***REMOVED***display:***REMOVED***grid;***REMOVED***grid-template-columns:***REMOVED***560px***REMOVED***1fr;***REMOVED***gap:***REMOVED***28px;***REMOVED***}
.left***REMOVED***{***REMOVED***display:***REMOVED***flex;***REMOVED***flex-direction:***REMOVED***column;***REMOVED***align-items:***REMOVED***center;***REMOVED***}
.disc-wrap***REMOVED***{***REMOVED***display:***REMOVED***grid;***REMOVED***place-items:***REMOVED***center;***REMOVED***}
.disc***REMOVED***{***REMOVED***width:***REMOVED***440px;***REMOVED***height:***REMOVED***440px;***REMOVED***border-radius:***REMOVED***50%;***REMOVED***background:***REMOVED***radial-gradient(#2b2f36***REMOVED***0%,***REMOVED***#151922***REMOVED***60%,***REMOVED***#0f1220***REMOVED***100%);***REMOVED***position:***REMOVED***relative;***REMOVED***box-shadow:***REMOVED***0***REMOVED***24px***REMOVED***48px***REMOVED***rgba(0,0,0,.35);***REMOVED***display:***REMOVED***grid;***REMOVED***place-items:***REMOVED***center;***REMOVED***overflow:***REMOVED***hidden;***REMOVED***}
.disc***REMOVED***img***REMOVED***{***REMOVED***width:***REMOVED***88%;***REMOVED***height:***REMOVED***88%;***REMOVED***border-radius:***REMOVED***50%;***REMOVED***object-fit:***REMOVED***cover;***REMOVED***filter:***REMOVED***contrast(1.05)***REMOVED***brightness(.98);***REMOVED***}
.center-hole***REMOVED***{***REMOVED***position:***REMOVED***absolute;***REMOVED***width:***REMOVED***18px;***REMOVED***height:***REMOVED***18px;***REMOVED***background:***REMOVED***#c7cad1;***REMOVED***border-radius:***REMOVED***50%;***REMOVED***box-shadow:***REMOVED***inset***REMOVED***0***REMOVED***0***REMOVED***0***REMOVED***4px***REMOVED***#2d3140;***REMOVED***}
.spinning***REMOVED***{***REMOVED***animation:***REMOVED***spin***REMOVED***14s***REMOVED***linear***REMOVED***infinite;***REMOVED***animation-play-state:***REMOVED***running;***REMOVED***}
.paused***REMOVED***{***REMOVED***animation-play-state:***REMOVED***paused;***REMOVED***}
@keyframes***REMOVED***spin***REMOVED***{***REMOVED***from***REMOVED***{***REMOVED***transform:***REMOVED***rotate(0deg);}***REMOVED***to***REMOVED***{***REMOVED***transform:***REMOVED***rotate(360deg);}***REMOVED***}
.tips***REMOVED***{***REMOVED***margin-top:***REMOVED***10px;***REMOVED***color:***REMOVED***rgba(255,255,255,.75);***REMOVED***font-size:***REMOVED***12px;***REMOVED***}
.controls***REMOVED***{***REMOVED***margin-top:***REMOVED***20px;***REMOVED***width:***REMOVED***100%;***REMOVED***display:***REMOVED***grid;***REMOVED***grid-template-columns:***REMOVED***auto***REMOVED***auto***REMOVED***auto***REMOVED***1fr;***REMOVED***align-items:***REMOVED***center;***REMOVED***gap:***REMOVED***12px;***REMOVED***}
.ctl***REMOVED***{***REMOVED***color:***REMOVED***#e5e7eb;***REMOVED***font-size:***REMOVED***18px;***REMOVED***}
.play***REMOVED***{***REMOVED***width:***REMOVED***46px;***REMOVED***height:***REMOVED***46px;***REMOVED***border:***REMOVED***none;***REMOVED***background:***REMOVED***linear-gradient(45deg,#67c3ff,#7b7cff);***REMOVED***}
.progress***REMOVED***{***REMOVED***display:***REMOVED***grid;***REMOVED***grid-template-columns:***REMOVED***54px***REMOVED***1fr***REMOVED***54px;***REMOVED***gap:***REMOVED***8px;***REMOVED***align-items:***REMOVED***center;***REMOVED***}
.time***REMOVED***{***REMOVED***color:***REMOVED***#d1d5db;***REMOVED***font-size:***REMOVED***12px;***REMOVED***text-align:***REMOVED***center;***REMOVED***}
.right***REMOVED***{***REMOVED***display:***REMOVED***flex;***REMOVED***flex-direction:***REMOVED***column;***REMOVED***}
.meta***REMOVED***.title***REMOVED***{***REMOVED***margin:***REMOVED***0***REMOVED***0***REMOVED***6px;***REMOVED***font-size:***REMOVED***28px;***REMOVED***font-weight:***REMOVED***800;***REMOVED***color:***REMOVED***#fff;***REMOVED***}
.meta***REMOVED***.artist***REMOVED***{***REMOVED***margin:***REMOVED***0***REMOVED***0***REMOVED***14px;***REMOVED***color:***REMOVED***#e5e7eb;***REMOVED***}
.lyrics***REMOVED***{***REMOVED***margin-top:***REMOVED***4px;***REMOVED***padding:***REMOVED***16px;***REMOVED***height:***REMOVED***560px;***REMOVED***overflow-y:***REMOVED***auto;***REMOVED***background:***REMOVED***rgba(6,10,25,.85);***REMOVED***border-radius:***REMOVED***14px;***REMOVED***color:***REMOVED***#e5e7eb;***REMOVED***box-shadow:***REMOVED***inset***REMOVED***0***REMOVED***8px***REMOVED***16px***REMOVED***rgba(0,0,0,.35);***REMOVED***backdrop-filter:***REMOVED***blur(2px);***REMOVED***}
.lyrics***REMOVED***.line***REMOVED***{***REMOVED***opacity:***REMOVED***.6;***REMOVED***padding:***REMOVED***6px***REMOVED***0;***REMOVED***transition:***REMOVED***opacity***REMOVED***.2s***REMOVED***ease;***REMOVED***}
.lyrics***REMOVED***.line.active***REMOVED***{***REMOVED***opacity:***REMOVED***1;***REMOVED***color:***REMOVED***#fff;***REMOVED***font-weight:***REMOVED***700;***REMOVED***}
.lyrics.empty***REMOVED***{***REMOVED***display:***REMOVED***grid;***REMOVED***place-items:***REMOVED***center;***REMOVED***color:***REMOVED***#b6bdc6;***REMOVED***}
@media***REMOVED***(max-width:***REMOVED***1024px)***REMOVED***{
***REMOVED******REMOVED***.player-page***REMOVED***{***REMOVED***grid-template-columns:***REMOVED***1fr;***REMOVED***}
***REMOVED******REMOVED***.disc***REMOVED***{***REMOVED***width:***REMOVED***320px;***REMOVED***height:***REMOVED***320px;***REMOVED***}
***REMOVED******REMOVED***.lyrics***REMOVED***{***REMOVED***height:***REMOVED***380px;***REMOVED***}
}
</style>

