<template>
***REMOVED******REMOVED***<div***REMOVED***class="profile">
***REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="card">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="card-header">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<h1>个人中心</h1>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="sub">管理你的头像与昵称信息</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-form***REMOVED***:model="form"***REMOVED***label-width="90px"***REMOVED***class="profile-form">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-form-item***REMOVED***label="头像">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="avatar-row">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="avatar-shadow">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<img***REMOVED***:src="form.avatar***REMOVED***||***REMOVED***defaultAvatar"***REMOVED***class="avatar"***REMOVED***alt="avatar"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="avatar-actions">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-upload
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:show-file-list="false"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:before-upload="beforeUpload"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:http-request="customUpload"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***accept="image/*"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-button***REMOVED***type="primary"***REMOVED***plain>上传头像</el-button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</el-upload>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="tip">支持***REMOVED***JPG/PNG，≤***REMOVED***2MB</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</el-form-item>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-form-item***REMOVED***label="昵称">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-input***REMOVED***v-model.trim="form.nickname"***REMOVED***maxlength="20"***REMOVED***show-word-limit***REMOVED***placeholder="请输入昵称"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</el-form-item>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-form-item>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-button***REMOVED***type="primary"***REMOVED***:loading="saving"***REMOVED***:disabled="!canSave"***REMOVED***@click="save">保存</el-button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-button***REMOVED***@click="reset">重置</el-button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</el-form-item>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</el-form>
***REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED***</div>
</template>

<script***REMOVED***setup***REMOVED***lang="ts">
import***REMOVED***{***REMOVED***ref,***REMOVED***computed***REMOVED***}***REMOVED***from***REMOVED***'vue'
import***REMOVED***{***REMOVED***useUserStore***REMOVED***}***REMOVED***from***REMOVED***'@/stores/user'

const***REMOVED***userStore***REMOVED***=***REMOVED***useUserStore()
const***REMOVED***defaultAvatar***REMOVED***=***REMOVED***'https://picsum.photos/80/80?random=3'

const***REMOVED***form***REMOVED***=***REMOVED***ref({
***REMOVED******REMOVED***avatar:***REMOVED***userStore.currentUser?.avatar***REMOVED***||***REMOVED***'',
***REMOVED******REMOVED***nickname:***REMOVED***userStore.currentUser?.nickname***REMOVED***||***REMOVED***''
})
const***REMOVED***origin***REMOVED***=***REMOVED***ref({
***REMOVED******REMOVED***avatar:***REMOVED***form.value.avatar,
***REMOVED******REMOVED***nickname:***REMOVED***form.value.nickname
})
const***REMOVED***saving***REMOVED***=***REMOVED***ref(false)
const***REMOVED***canSave***REMOVED***=***REMOVED***computed(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***return***REMOVED***!!form.value.nickname***REMOVED***&&***REMOVED***(form.value.nickname***REMOVED***!==***REMOVED***origin.value.nickname***REMOVED***||***REMOVED***form.value.avatar***REMOVED***!==***REMOVED***origin.value.avatar)
})

const***REMOVED***beforeUpload***REMOVED***=***REMOVED***(file:***REMOVED***File)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***isImage***REMOVED***=***REMOVED***file.type.startsWith('image/')
***REMOVED******REMOVED***const***REMOVED***isLt2M***REMOVED***=***REMOVED***file.size***REMOVED***/***REMOVED***1024***REMOVED***/***REMOVED***1024***REMOVED***<***REMOVED***2
***REMOVED******REMOVED***if***REMOVED***(!isImage)***REMOVED***alert('请上传图片文件')
***REMOVED******REMOVED***if***REMOVED***(!isLt2M)***REMOVED***alert('图片大小需小于2MB')
***REMOVED******REMOVED***return***REMOVED***isImage***REMOVED***&&***REMOVED***isLt2M
}

const***REMOVED***customUpload***REMOVED***=***REMOVED***async***REMOVED***(options:***REMOVED***any)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***file***REMOVED***=***REMOVED***options.file***REMOVED***as***REMOVED***File
***REMOVED******REMOVED***//***REMOVED***简化：本地预览+Base64存储（生产应上传到服务器）
***REMOVED******REMOVED***const***REMOVED***reader***REMOVED***=***REMOVED***new***REMOVED***FileReader()
***REMOVED******REMOVED***reader.onload***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***form.value.avatar***REMOVED***=***REMOVED***reader.result***REMOVED***as***REMOVED***string
***REMOVED******REMOVED***}
***REMOVED******REMOVED***reader.readAsDataURL(file)
***REMOVED******REMOVED***options.onSuccess***REMOVED***&&***REMOVED***options.onSuccess({},***REMOVED***file)
}

const***REMOVED***save***REMOVED***=***REMOVED***async***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!form.value.nickname)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***{***REMOVED***ElMessage***REMOVED***}***REMOVED***=***REMOVED***await***REMOVED***import('element-plus')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ElMessage.warning('请输入昵称')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***saving.value***REMOVED***=***REMOVED***true
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***仅提交有改动的字段，未改动传***REMOVED***null（后端***REMOVED***COALESCE***REMOVED***保持原值）
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***payload:***REMOVED***any***REMOVED***=***REMOVED***{}
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(form.value.nickname***REMOVED***!==***REMOVED***origin.value.nickname)***REMOVED***payload.nickname***REMOVED***=***REMOVED***form.value.nickname
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(form.value.avatar***REMOVED***!==***REMOVED***origin.value.avatar)***REMOVED***payload.avatar***REMOVED***=***REMOVED***form.value.avatar

***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***resp***REMOVED***=***REMOVED***await***REMOVED***fetch(`/api/user/info/${userStore.currentUser?.id}`,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***method:***REMOVED***'PUT',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***headers:***REMOVED***{***REMOVED***'Content-Type':***REMOVED***'application/json'***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***body:***REMOVED***JSON.stringify(Object.keys(payload).length***REMOVED***?***REMOVED***payload***REMOVED***:***REMOVED***{***REMOVED***nickname:***REMOVED***null,***REMOVED***avatar:***REMOVED***null***REMOVED***})
***REMOVED******REMOVED******REMOVED******REMOVED***})
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***result***REMOVED***=***REMOVED***await***REMOVED***resp.json()
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(result.code***REMOVED***===***REMOVED***200)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***更新本地用户信息（仅同步改动字段）
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(userStore.currentUser)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(payload.nickname***REMOVED***!==***REMOVED***undefined)***REMOVED***userStore.currentUser.nickname***REMOVED***=***REMOVED***form.value.nickname
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(payload.avatar***REMOVED***!==***REMOVED***undefined)***REMOVED***userStore.currentUser.avatar***REMOVED***=***REMOVED***form.value.avatar
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***同步到本地存储
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***localStorage.setItem('currentUser',***REMOVED***JSON.stringify(userStore.currentUser))
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***origin.value***REMOVED***=***REMOVED***{***REMOVED***...form.value***REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***{***REMOVED***ElMessage***REMOVED***}***REMOVED***=***REMOVED***await***REMOVED***import('element-plus')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ElMessage.success('保存成功')
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***{***REMOVED***ElMessage***REMOVED***}***REMOVED***=***REMOVED***await***REMOVED***import('element-plus')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ElMessage.error(result.message***REMOVED***||***REMOVED***'保存失败')
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(e)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***{***REMOVED***ElMessage***REMOVED***}***REMOVED***=***REMOVED***await***REMOVED***import('element-plus')
***REMOVED******REMOVED******REMOVED******REMOVED***ElMessage.error('网络异常')
***REMOVED******REMOVED***}***REMOVED***finally***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***saving.value***REMOVED***=***REMOVED***false
***REMOVED******REMOVED***}
}

const***REMOVED***reset***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***form.value***REMOVED***=***REMOVED***{***REMOVED***...origin.value***REMOVED***}
}
</script>

<style***REMOVED***scoped>
.profile***REMOVED***{***REMOVED***max-width:***REMOVED***840px;***REMOVED***margin:***REMOVED***24px***REMOVED***auto;***REMOVED***padding:***REMOVED***0***REMOVED***16px;***REMOVED***}
.card***REMOVED***{***REMOVED***background:***REMOVED***#fff;***REMOVED***border-radius:***REMOVED***16px;***REMOVED***box-shadow:***REMOVED***0***REMOVED***8px***REMOVED***24px***REMOVED***rgba(0,0,0,.06);***REMOVED***overflow:***REMOVED***hidden;***REMOVED***}
.card-header***REMOVED***{***REMOVED***padding:***REMOVED***20px***REMOVED***24px***REMOVED***0***REMOVED***24px;***REMOVED***}
.card-header***REMOVED***h1***REMOVED***{***REMOVED***margin:***REMOVED***0;***REMOVED***color:***REMOVED***#1f2328;***REMOVED***font-size:***REMOVED***28px;***REMOVED***}
.card-header***REMOVED***.sub***REMOVED***{***REMOVED***color:***REMOVED***#8a919f;***REMOVED***font-size:***REMOVED***13px;***REMOVED***margin-top:***REMOVED***6px;***REMOVED***}
.profile-form***REMOVED***{***REMOVED***padding:***REMOVED***16px***REMOVED***24px***REMOVED***24px;***REMOVED***}
.avatar-row***REMOVED***{***REMOVED***display:***REMOVED***flex;***REMOVED***align-items:***REMOVED***center;***REMOVED***gap:***REMOVED***16px;***REMOVED***}
.avatar-shadow***REMOVED***{***REMOVED***width:***REMOVED***96px;***REMOVED***height:***REMOVED***96px;***REMOVED***border-radius:***REMOVED***50%;***REMOVED***padding:***REMOVED***2px;***REMOVED***background:***REMOVED***linear-gradient(135deg,#e3e8ef,#f5f7fb);***REMOVED***box-shadow:***REMOVED***0***REMOVED***6px***REMOVED***16px***REMOVED***rgba(0,0,0,.08);***REMOVED***}
.avatar***REMOVED***{***REMOVED***width:***REMOVED***92px;***REMOVED***height:***REMOVED***92px;***REMOVED***border-radius:***REMOVED***50%;***REMOVED***object-fit:***REMOVED***cover;***REMOVED***display:***REMOVED***block;***REMOVED***}
.avatar-actions***REMOVED***{***REMOVED***display:***REMOVED***flex;***REMOVED***flex-direction:***REMOVED***column;***REMOVED***gap:***REMOVED***6px;***REMOVED***}
.tip***REMOVED***{***REMOVED***font-size:***REMOVED***12px;***REMOVED***color:***REMOVED***#9aa5b1;***REMOVED***}
</style>

