<template>
***REMOVED******REMOVED***<div***REMOVED***class="profile">
***REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="card">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="card-header">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<h1>个人中心</h1>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="sub">管理你的头像与昵称信息</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-form***REMOVED***:model="form"***REMOVED***label-width="90px"***REMOVED***class="profile-form">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-form-item***REMOVED***label="头像">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="avatar-row">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="avatar-shadow">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<img***REMOVED***:src="avatarSrc"***REMOVED***class="avatar"***REMOVED***alt="avatar"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="avatar-actions">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-upload
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:show-file-list="false"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:before-upload="beforeUpload"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***:http-request="customUpload"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***accept="image/*"
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-button***REMOVED***type="primary"***REMOVED***plain>上传头像</el-button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</el-upload>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="tip">支持***REMOVED***JPG/PNG，≤***REMOVED***2MB</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</el-form-item>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-form-item***REMOVED***label="昵称">
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-input***REMOVED***v-model.trim="form.nickname"***REMOVED***maxlength="20"***REMOVED***show-word-limit***REMOVED***placeholder="请输入昵称"***REMOVED***/>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</el-form-item>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-form-item>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-button***REMOVED***type="primary"***REMOVED***:loading="saving"***REMOVED***:disabled="!canSave"***REMOVED***@click="save">保存</el-button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<el-button***REMOVED***@click="reset">重置</el-button>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***<div***REMOVED***class="tip">可以单独修改头像或昵称，也可以同时修改</div>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</el-form-item>
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***</el-form>
***REMOVED******REMOVED******REMOVED******REMOVED***</div>
***REMOVED******REMOVED***</div>
</template>

<script***REMOVED***setup***REMOVED***lang="ts">
import***REMOVED***{***REMOVED***ref,***REMOVED***computed,***REMOVED***onMounted,***REMOVED***watch***REMOVED***}***REMOVED***from***REMOVED***'vue'
import***REMOVED***{***REMOVED***useUserStore***REMOVED***}***REMOVED***from***REMOVED***'@/stores/user'

const***REMOVED***userStore***REMOVED***=***REMOVED***useUserStore()
const***REMOVED***defaultAvatar***REMOVED***=***REMOVED***'https://picsum.photos/80/80?random=3'

const***REMOVED***form***REMOVED***=***REMOVED***ref({
***REMOVED******REMOVED***//***REMOVED***avatar***REMOVED***字段可为***REMOVED***File***REMOVED***或***REMOVED***string(URL)
***REMOVED******REMOVED***avatar:***REMOVED***'',
***REMOVED******REMOVED***nickname:***REMOVED***''
})
const***REMOVED***previewUrl***REMOVED***=***REMOVED***ref<string>(defaultAvatar)
const***REMOVED***origin***REMOVED***=***REMOVED***ref({
***REMOVED******REMOVED***avatar:***REMOVED***'',
***REMOVED******REMOVED***nickname:***REMOVED***''
})

//***REMOVED***初始化表单数据
const***REMOVED***initForm***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***if***REMOVED***(userStore.currentUser)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***form.value***REMOVED***=***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***avatar:***REMOVED***(userStore.currentUser.avatar***REMOVED***as***REMOVED***any)***REMOVED***||***REMOVED***'',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***nickname:***REMOVED***userStore.currentUser.nickname***REMOVED***||***REMOVED***''
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***previewUrl.value***REMOVED***=***REMOVED***userStore.currentUser.avatar***REMOVED***||***REMOVED***defaultAvatar
***REMOVED******REMOVED******REMOVED******REMOVED***origin.value***REMOVED***=***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***avatar:***REMOVED***typeof***REMOVED***form.value.avatar***REMOVED***===***REMOVED***'string'***REMOVED***?***REMOVED***(form.value.avatar***REMOVED***as***REMOVED***string)***REMOVED***:***REMOVED***'',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***nickname:***REMOVED***form.value.nickname
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***}
}

//***REMOVED***监听用户信息变化
watch(()***REMOVED***=>***REMOVED***userStore.currentUser,***REMOVED***(newUser)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***if***REMOVED***(newUser)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***initForm()
***REMOVED******REMOVED***}
},***REMOVED***{***REMOVED***immediate:***REMOVED***true***REMOVED***})

onMounted(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***//***REMOVED***确保用户信息已加载
***REMOVED******REMOVED***if***REMOVED***(userStore.currentUser)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***initForm()
***REMOVED******REMOVED***}
})
const***REMOVED***avatarSrc***REMOVED***=***REMOVED***computed(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***//***REMOVED***如果***REMOVED***form.avatar***REMOVED***是字符串（Base64***REMOVED***或***REMOVED***URL），直接使用
***REMOVED******REMOVED***if***REMOVED***(typeof***REMOVED***form.value.avatar***REMOVED***===***REMOVED***'string'***REMOVED***&&***REMOVED***form.value.avatar)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***form.value.avatar
***REMOVED******REMOVED***}
***REMOVED******REMOVED***//***REMOVED***如果***REMOVED***form.avatar***REMOVED***是***REMOVED***File***REMOVED***对象，使用***REMOVED***previewUrl
***REMOVED******REMOVED***if***REMOVED***(typeof***REMOVED***form.value.avatar***REMOVED***===***REMOVED***'object'***REMOVED***&&***REMOVED***form.value.avatar)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***return***REMOVED***previewUrl.value***REMOVED***||***REMOVED***defaultAvatar
***REMOVED******REMOVED***}
***REMOVED******REMOVED***//***REMOVED***默认情况，使用用户存储的头像或默认头像
***REMOVED******REMOVED***return***REMOVED***userStore.currentUser?.avatar***REMOVED***||***REMOVED***defaultAvatar
})
const***REMOVED***saving***REMOVED***=***REMOVED***ref(false)
const***REMOVED***canSave***REMOVED***=***REMOVED***computed(()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***//***REMOVED***只要有昵称或头像的变化就可以保存
***REMOVED******REMOVED***return***REMOVED***(form.value.nickname***REMOVED***!==***REMOVED***origin.value.nickname***REMOVED***||***REMOVED***form.value.avatar***REMOVED***!==***REMOVED***origin.value.avatar)
})

const***REMOVED***beforeUpload***REMOVED***=***REMOVED***(file:***REMOVED***File)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***isImage***REMOVED***=***REMOVED***file.type.startsWith('image/')
***REMOVED******REMOVED***const***REMOVED***isLt2M***REMOVED***=***REMOVED***file.size***REMOVED***/***REMOVED***1024***REMOVED***/***REMOVED***1024***REMOVED***<***REMOVED***2
***REMOVED******REMOVED***if***REMOVED***(!isImage)***REMOVED***alert('请上传图片文件')
***REMOVED******REMOVED***if***REMOVED***(!isLt2M)***REMOVED***alert('图片大小需小于2MB')
***REMOVED******REMOVED***return***REMOVED***isImage***REMOVED***&&***REMOVED***isLt2M
}

const***REMOVED***customUpload***REMOVED***=***REMOVED***async***REMOVED***(options:***REMOVED***any)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***const***REMOVED***file***REMOVED***=***REMOVED***options.file***REMOVED***as***REMOVED***File
***REMOVED******REMOVED***//***REMOVED***仅做本地预览与缓存***REMOVED***File；真正保存时上传到***REMOVED***OSS
***REMOVED******REMOVED***if***REMOVED***(previewUrl.value***REMOVED***&&***REMOVED***previewUrl.value.startsWith('blob:'))***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***URL.revokeObjectURL(previewUrl.value)
***REMOVED******REMOVED***}
***REMOVED******REMOVED***previewUrl.value***REMOVED***=***REMOVED***URL.createObjectURL(file)
***REMOVED******REMOVED***form.value.avatar***REMOVED***=***REMOVED***file***REMOVED***as***REMOVED***any
***REMOVED******REMOVED***options.onSuccess***REMOVED***&&***REMOVED***options.onSuccess({},***REMOVED***file)
}

const***REMOVED***save***REMOVED***=***REMOVED***async***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***try***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(!form.value.nickname)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***{***REMOVED***ElMessage***REMOVED***}***REMOVED***=***REMOVED***await***REMOVED***import('element-plus')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ElMessage.warning('请输入昵称')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED***saving.value***REMOVED***=***REMOVED***true
***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***若头像为***REMOVED***File，转换为压缩的***REMOVED***Base64***REMOVED***保存到数据库
***REMOVED******REMOVED******REMOVED******REMOVED***let***REMOVED***avatarUrl:***REMOVED***string***REMOVED***|***REMOVED***undefined
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(form.value.avatar***REMOVED***&&***REMOVED***typeof***REMOVED***form.value.avatar***REMOVED***!==***REMOVED***'string')***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***file***REMOVED***=***REMOVED***form.value.avatar***REMOVED***as***REMOVED***File
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***检查文件大小，限制在***REMOVED***1MB***REMOVED***以内
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(file.size***REMOVED***>***REMOVED***1024***REMOVED*******REMOVED***1024)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***{***REMOVED***ElMessage***REMOVED***}***REMOVED***=***REMOVED***await***REMOVED***import('element-plus')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ElMessage.error('头像文件大小不能超过***REMOVED***1MB')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***saving.value***REMOVED***=***REMOVED***false
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***return
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***压缩图片并转换为***REMOVED***Base64
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***avatarUrl***REMOVED***=***REMOVED***await***REMOVED***new***REMOVED***Promise<string>((resolve,***REMOVED***reject)***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***canvas***REMOVED***=***REMOVED***document.createElement('canvas')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***ctx***REMOVED***=***REMOVED***canvas.getContext('2d')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***img***REMOVED***=***REMOVED***new***REMOVED***Image()
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***img.onload***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***计算保持比例的尺寸
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***maxSize***REMOVED***=***REMOVED***200
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***let***REMOVED***{***REMOVED***width,***REMOVED***height***REMOVED***}***REMOVED***=***REMOVED***img
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***如果图片比最大尺寸小，保持原尺寸
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(width***REMOVED***<=***REMOVED***maxSize***REMOVED***&&***REMOVED***height***REMOVED***<=***REMOVED***maxSize)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***canvas.width***REMOVED***=***REMOVED***width
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***canvas.height***REMOVED***=***REMOVED***height
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ctx?.drawImage(img,***REMOVED***0,***REMOVED***0,***REMOVED***width,***REMOVED***height)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***按比例缩放到最大尺寸
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***ratio***REMOVED***=***REMOVED***Math.min(maxSize***REMOVED***/***REMOVED***width,***REMOVED***maxSize***REMOVED***/***REMOVED***height)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***newWidth***REMOVED***=***REMOVED***Math.round(width***REMOVED*******REMOVED***ratio)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***newHeight***REMOVED***=***REMOVED***Math.round(height***REMOVED*******REMOVED***ratio)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***canvas.width***REMOVED***=***REMOVED***newWidth
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***canvas.height***REMOVED***=***REMOVED***newHeight
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ctx?.drawImage(img,***REMOVED***0,***REMOVED***0,***REMOVED***newWidth,***REMOVED***newHeight)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***转换为***REMOVED***Base64，使用较低的质量
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***compressedBase64***REMOVED***=***REMOVED***canvas.toDataURL('image/jpeg',***REMOVED***0.7)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***resolve(compressedBase64)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***img.onerror***REMOVED***=***REMOVED***reject
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***img.src***REMOVED***=***REMOVED***URL.createObjectURL(file)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***})
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***
***REMOVED******REMOVED******REMOVED******REMOVED***}

***REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***仅提交有改动的字段，未改动传***REMOVED***null（后端***REMOVED***COALESCE***REMOVED***保持原值）
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***payload:***REMOVED***any***REMOVED***=***REMOVED***{}
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(form.value.nickname***REMOVED***!==***REMOVED***origin.value.nickname)***REMOVED***payload.nickname***REMOVED***=***REMOVED***form.value.nickname
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(avatarUrl)***REMOVED***payload.avatar***REMOVED***=***REMOVED***avatarUrl
***REMOVED******REMOVED******REMOVED******REMOVED***else***REMOVED***if***REMOVED***(typeof***REMOVED***form.value.avatar***REMOVED***===***REMOVED***'string'***REMOVED***&&***REMOVED***form.value.avatar***REMOVED***!==***REMOVED***origin.value.avatar)***REMOVED***payload.avatar***REMOVED***=***REMOVED***form.value.avatar


***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***resp***REMOVED***=***REMOVED***await***REMOVED***fetch(`/api/user/info/${userStore.currentUser?.id}`,***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***method:***REMOVED***'PUT',
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***headers:***REMOVED***{***REMOVED***'Content-Type':***REMOVED***'application/json'***REMOVED***},
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***body:***REMOVED***JSON.stringify(Object.keys(payload).length***REMOVED***?***REMOVED***payload***REMOVED***:***REMOVED***{***REMOVED***nickname:***REMOVED***null,***REMOVED***avatar:***REMOVED***null***REMOVED***})
***REMOVED******REMOVED******REMOVED******REMOVED***})
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***result***REMOVED***=***REMOVED***await***REMOVED***resp.json()
***REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(result.code***REMOVED***===***REMOVED***200)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***更新本地用户信息（仅同步改动字段）
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(userStore.currentUser)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(payload.nickname***REMOVED***!==***REMOVED***undefined)***REMOVED***userStore.currentUser.nickname***REMOVED***=***REMOVED***form.value.nickname
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(payload.avatar***REMOVED***!==***REMOVED***undefined)***REMOVED***userStore.currentUser.avatar***REMOVED***=***REMOVED***payload.avatar
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***同步到本地存储
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***localStorage.setItem('userInfo',***REMOVED***JSON.stringify(userStore.currentUser))
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***保存后，将本地状态归一化为***REMOVED***Base64***REMOVED***字符串
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(payload.avatar)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***form.value.avatar***REMOVED***=***REMOVED***payload.avatar
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***清理***REMOVED***blob***REMOVED***URL
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***if***REMOVED***(previewUrl.value***REMOVED***&&***REMOVED***previewUrl.value.startsWith('blob:'))***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***URL.revokeObjectURL(previewUrl.value)
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***更新预览***REMOVED***URL***REMOVED***为保存的***REMOVED***Base64
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***previewUrl.value***REMOVED***=***REMOVED***payload.avatar
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***//***REMOVED***更新原始状态，避免重复保存
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***origin.value***REMOVED***=***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***avatar:***REMOVED***payload.avatar***REMOVED***||***REMOVED***form.value.avatar,
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***nickname:***REMOVED***form.value.nickname
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***{***REMOVED***ElMessage***REMOVED***}***REMOVED***=***REMOVED***await***REMOVED***import('element-plus')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ElMessage.success('保存成功')
***REMOVED******REMOVED******REMOVED******REMOVED***}***REMOVED***else***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***{***REMOVED***ElMessage***REMOVED***}***REMOVED***=***REMOVED***await***REMOVED***import('element-plus')
***REMOVED******REMOVED******REMOVED******REMOVED******REMOVED******REMOVED***ElMessage.error(result.message***REMOVED***||***REMOVED***'保存失败')
***REMOVED******REMOVED******REMOVED******REMOVED***}
***REMOVED******REMOVED***}***REMOVED***catch***REMOVED***(e)***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***const***REMOVED***{***REMOVED***ElMessage***REMOVED***}***REMOVED***=***REMOVED***await***REMOVED***import('element-plus')
***REMOVED******REMOVED******REMOVED******REMOVED***ElMessage.error('网络异常')
***REMOVED******REMOVED***}***REMOVED***finally***REMOVED***{
***REMOVED******REMOVED******REMOVED******REMOVED***saving.value***REMOVED***=***REMOVED***false
***REMOVED******REMOVED***}
}

const***REMOVED***reset***REMOVED***=***REMOVED***()***REMOVED***=>***REMOVED***{
***REMOVED******REMOVED***form.value***REMOVED***=***REMOVED***{***REMOVED***...origin.value***REMOVED***}
}
</script>

<style***REMOVED***scoped>
.profile***REMOVED***{***REMOVED***max-width:***REMOVED***840px;***REMOVED***margin:***REMOVED***24px***REMOVED***auto;***REMOVED***padding:***REMOVED***0***REMOVED***16px;***REMOVED***}
.card***REMOVED***{***REMOVED***background:***REMOVED***#fff;***REMOVED***border-radius:***REMOVED***16px;***REMOVED***box-shadow:***REMOVED***0***REMOVED***8px***REMOVED***24px***REMOVED***rgba(0,0,0,.06);***REMOVED***overflow:***REMOVED***hidden;***REMOVED***}
.card-header***REMOVED***{***REMOVED***padding:***REMOVED***20px***REMOVED***24px***REMOVED***0***REMOVED***24px;***REMOVED***}
.card-header***REMOVED***h1***REMOVED***{***REMOVED***margin:***REMOVED***0;***REMOVED***color:***REMOVED***#1f2328;***REMOVED***font-size:***REMOVED***28px;***REMOVED***}
.card-header***REMOVED***.sub***REMOVED***{***REMOVED***color:***REMOVED***#8a919f;***REMOVED***font-size:***REMOVED***13px;***REMOVED***margin-top:***REMOVED***6px;***REMOVED***}
.profile-form***REMOVED***{***REMOVED***padding:***REMOVED***16px***REMOVED***24px***REMOVED***24px;***REMOVED***}
.avatar-row***REMOVED***{***REMOVED***display:***REMOVED***flex;***REMOVED***align-items:***REMOVED***center;***REMOVED***gap:***REMOVED***16px;***REMOVED***}
.avatar-shadow***REMOVED***{***REMOVED***width:***REMOVED***96px;***REMOVED***height:***REMOVED***96px;***REMOVED***border-radius:***REMOVED***50%;***REMOVED***padding:***REMOVED***2px;***REMOVED***background:***REMOVED***linear-gradient(135deg,#e3e8ef,#f5f7fb);***REMOVED***box-shadow:***REMOVED***0***REMOVED***6px***REMOVED***16px***REMOVED***rgba(0,0,0,.08);***REMOVED***}
.avatar***REMOVED***{***REMOVED***width:***REMOVED***92px;***REMOVED***height:***REMOVED***92px;***REMOVED***border-radius:***REMOVED***50%;***REMOVED***object-fit:***REMOVED***cover;***REMOVED***display:***REMOVED***block;***REMOVED***}
.avatar-actions***REMOVED***{***REMOVED***display:***REMOVED***flex;***REMOVED***flex-direction:***REMOVED***column;***REMOVED***gap:***REMOVED***6px;***REMOVED***}
.tip***REMOVED***{***REMOVED***font-size:***REMOVED***12px;***REMOVED***color:***REMOVED***#9aa5b1;***REMOVED***}
</style>

